# Numpy and Pandas Assignment 

#### Submitted by Ishwor Baral

In [2]:
import numpy as np
import pandas as pd

### 1. Numpy Basics

In [6]:
# create 1d Array
arr_1d = np.array([1,2,3])
print("1D Array:\n", arr_1d)

1D Array:
 [1 2 3]


In [4]:
# Create 2d Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


### 2.Array Operations

In [7]:
# Perform basic arithmetic operations on the arrays
arr_1d_add = arr_1d + 10
arr_2d_mult = arr_2d * 2
print("1D Array + 10:", arr_1d_add)
print("2D Array * 2:\n", arr_2d_mult)

1D Array + 10: [11 12 13]
2D Array * 2:
 [[ 2  4  6]
 [ 8 10 12]]


### 3. Indexing and Slicing

In [8]:
# Demonstrate indexing and slicing on the arrays
print("First element of 1D array:", arr_1d[0])
print("First row of 2D array:\n", arr_2d[0, :])

First element of 1D array: 1
First row of 2D array:
 [1 2 3]


### 4. Shape and Reshape

In [9]:
# Show how to check the shape of an array and reshape it
print("Shape of 2D array:", arr_2d.shape)
reshaped_arr = arr_2d.reshape((3, 2))
print("Reshaped 2D Array:\n", reshaped_arr)

Shape of 2D array: (2, 3)
Reshaped 2D Array:
 [[1 2]
 [3 4]
 [5 6]]
